"""Add Score Table for History of Daily Game

Revision ID: 68b78093e89f
Revises: 806b6f512089
Create Date: 2026-05-13 13:07:43.609574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b78093e89f'
down_revision = '806b6f512089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reset_date')
    )
    with op.batch_alter_table('daily_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_score_reset_date'), ['reset_date'], unique=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('time_taken',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('time_taken',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('daily_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_score_reset_date'))

    op.drop_table('daily_score')
    # ### end Alembic commands ###
