"""empty message

Revision ID: 806b6f512089
Revises: e69d8902dbfb
Create Date: 2026-05-10 18:10:52.886386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806b6f512089'
down_revision = 'e69d8902dbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_movie_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.Date(), nullable=False),
    sa.Column('movie_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_movie_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_movie_set_reset_date'), ['reset_date'], unique=True)

    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_refresh', sa.DateTime(), nullable=True),
    sa.Column('next_popular_page', sa.Integer(), nullable=True),
    sa.Column('next_top_rated_page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    with op.batch_alter_table('daily_movie_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_movie_set_reset_date'))

    op.drop_table('daily_movie_set')
    # ### end Alembic commands ###
